// resources/js/Pages/Eps/Create.vue
<template>
    <Head title="Crear EPS" />

    <AuthenticatedLayout>
        <template #header>
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">Crear Nueva EPS</h2>
        </template>

        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                    <div class="p-6 text-gray-900">
                        <form @submit.prevent="submit" class="space-y-6">
                            <div>
                                <InputLabel for="entidad" value="Entidad" />
                                <TextInput
                                    id="entidad"
                                    type="text"
                                    class="mt-1 block w-full"
                                    v-model="form.entidad"
                                    required
                                />
                                <InputError :message="form.errors.entidad" class="mt-2" />
                            </div>

                            <div>
                                <InputLabel for="codigo" value="Código" />
                                <TextInput
                                    id="codigo"
                                    type="text"
                                    class="mt-1 block w-full"
                                    v-model="form.codigo"
                                    required
                                />
                                <InputError :message="form.errors.codigo" class="mt-2" />
                            </div>

                            <div>
                                <InputLabel for="codigo_movilidad" value="Código Movilidad" />
                                <TextInput
                                    id="codigo_movilidad"
                                    type="text"
                                    class="mt-1 block w-full"
                                    v-model="form.codigo_movilidad"
                                />
                                <InputError :message="form.errors.codigo_movilidad" class="mt-2" />
                            </div>

                            <div>
                                <InputLabel for="nit" value="NIT" />
                                <TextInput
                                    id="nit"
                                    type="text"
                                    class="mt-1 block w-full"
                                    v-model="form.nit"
                                    required
                                />
                                <InputError :message="form.errors.nit" class="mt-2" />
                            </div>

                            <div>
                                <InputLabel for="regimen" value="Régimen" />
                                <select
                                    id="regimen"
                                    class="mt-1 block w-full border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm"
                                    v-model="form.regimen"
                                    required
                                >
                                    <option value="">Seleccione un régimen</option>
                                    <option value="CONTRIBUTIVO">CONTRIBUTIVO</option>
                                    <option value="SUBSIDIADO">SUBSIDIADO</option>
                                    <option value="AMBOS REGÍMENES">AMBOS REGÍMENES</option>
                                    <option value="No Aplica">No Aplica</option>
                                </select>
                                <InputError :message="form.errors.regimen" class="mt-2" />
                            </div>

                            <div class="flex items-center justify-end mt-4">
                                <Link
                                    :href="route('eps.index')"
                                    class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded mr-2"
                                >
                                    Cancelar
                                </Link>
                                <PrimaryButton class="ml-4" :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                                    Crear EPS
                                </PrimaryButton>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </AuthenticatedLayout>
</template>

<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';

const form = useForm({
    entidad: '',
    codigo: '',
    codigo_movilidad: '',
    nit: '',
    regimen: '',
});

const submit = () => {
    form.post(route('eps.store'));
};
</script>

// resources/js/Pages/Cie10/Create.jsx
import { useState } from 'react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, useForm } from '@inertiajs/react';
import InputError from '@/Components/InputError';
import InputLabel from '@/Components/InputLabel';
import PrimaryButton from '@/Components/PrimaryButton';
import TextInput from '@/Components/TextInput';

export default function Create({ auth }) {
    const form = useForm({
        code: '',
        description: '',
    });

    const submit = (e) => {
        e.preventDefault();
        form.post(route('cie10.store'));
    };

    return (
        <AuthenticatedLayout
            user={auth.user}
            header={<h2 className="font-semibold text-xl text-gray-800 leading-tight">Crear CIE10</h2>}
        >
            <Head title="Crear CIE10" />

            <div className="py-12">
                <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                    <div className="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                        <div className="p-6 text-gray-900">
                            <form onSubmit={submit} className="space-y-6">
                                <div>
                                    <InputLabel htmlFor="code" value="Código" />
                                    <TextInput
                                        id="code"
                                        type="text"
                                        className="mt-1 block w-full"
                                        value={form.data.code}
                                        onChange={e => form.setData('code', e.target.value)}
                                        maxLength="10"
                                        required
                                    />
                                    <InputError message={form.errors.code} className="mt-2" />
                                </div>

                                <div>
                                    <InputLabel htmlFor="description" value="Descripción" />
                                    <TextInput
                                        id="description"
                                        type="text"
                                        className="mt-1 block w-full"
                                        value={form.data.description}
                                        onChange={e => form.setData('description', e.target.value)}
                                        maxLength="255"
                                        required
                                    />
                                    <InputError message={form.errors.description} className="mt-2" />
                                </div>

                                <div className="flex items-center justify-end mt-4">
                                    <Link
                                        href={route('cie10.index')}
                                        className="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded mr-2"
                                    >
                                        Cancelar
                                    </Link>
                                    <PrimaryButton className="ml-4" disabled={form.processing}>
                                        Crear CIE10
                                    </PrimaryButton>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </AuthenticatedLayout>
    );
}
